/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mail_send;

import java.awt.Color;
import java.io.File;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author renat
 */
public class MailSender extends javax.swing.JFrame {

    /**
     * Creates new form Email
     */
    private int xMouse  = 0;
    private int yMouse  = 0;
    
    public MailSender() {
        initComponents();
    }
    public String sendMail(String Remetente,String Senha,String Destinatario,String Assunto,String TextMensagem, String txtFile){

	String Msg;
    
        final String usuario = Remetente;
        final String senha = Senha;
        
        Properties props = new Properties();
        props.put("mail.smtp.auth", true);
        props.put("mail.smtp.starttls.enable", true);
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.setProperty("mail.smtp.ssl.trust", "smtp.gmail.com");

        Session session = Session.getInstance(props, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(usuario, senha);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(Remetente));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(Destinatario));
            message.setSubject(Assunto);
            message.setText(TextMensagem);
            message.setText(txtFile);
            Transport.send(message);
            Msg="true";
    	    return Msg;

        } catch (MessagingException e) {
            return e.toString();
        }
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDestinatario = new javax.swing.JLabel();
        jLabelAssunto = new javax.swing.JLabel();
        jLabelMensagem = new javax.swing.JLabel();
        jButtonEnviar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ImageIconMail = new javax.swing.JLabel();
        jButtonNovaMensagem = new javax.swing.JButton();
        jButtonAnexar = new javax.swing.JButton();
        Assunto = new javax.swing.JTextField();
        Destinatario = new javax.swing.JTextField();
        Dragged = new javax.swing.JPanel();
        jButtonMinimizar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelRemetente = new javax.swing.JLabel();
        Remetente = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        Senha = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMensagem = new javax.swing.JTextArea();
        txtFile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(null);

        jLabelDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDestinatario.setText("Destinatário:");
        jPanel1.add(jLabelDestinatario);
        jLabelDestinatario.setBounds(170, 210, 120, 14);

        jLabelAssunto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAssunto.setText("Assunto:");
        jPanel1.add(jLabelAssunto);
        jLabelAssunto.setBounds(170, 260, 120, 14);

        jLabelMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMensagem.setText("Mensagem:");
        jPanel1.add(jLabelMensagem);
        jLabelMensagem.setBounds(170, 310, 130, 14);

        jButtonEnviar.setBackground(new java.awt.Color(0, 153, 153));
        jButtonEnviar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEnviarMouseExited(evt);
            }
        });
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEnviar);
        jButtonEnviar.setBounds(170, 510, 370, 30);

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));

        ImageIconMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mail_send/img/icon-email.png"))); // NOI18N

        jButtonNovaMensagem.setBackground(new java.awt.Color(0, 153, 153));
        jButtonNovaMensagem.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonNovaMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNovaMensagem.setText("Nova mensagem");
        jButtonNovaMensagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovaMensagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNovaMensagemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNovaMensagemMouseExited(evt);
            }
        });
        jButtonNovaMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaMensagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageIconMail, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
            .addComponent(jButtonNovaMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 351, Short.MAX_VALUE)
                .addComponent(jButtonNovaMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImageIconMail, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 30, 127, 530);

        jButtonAnexar.setBackground(new java.awt.Color(0, 153, 153));
        jButtonAnexar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mail_send/img/icon-anexo.png"))); // NOI18N
        jButtonAnexar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnexarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAnexar);
        jButtonAnexar.setBounds(170, 470, 30, 30);

        Assunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssuntoActionPerformed(evt);
            }
        });
        jPanel1.add(Assunto);
        Assunto.setBounds(170, 280, 370, 25);

        Destinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinatarioActionPerformed(evt);
            }
        });
        jPanel1.add(Destinatario);
        Destinatario.setBounds(170, 230, 370, 25);

        Dragged.setBackground(new java.awt.Color(255, 255, 255));
        Dragged.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DraggedMouseDragged(evt);
            }
        });
        Dragged.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DraggedMousePressed(evt);
            }
        });

        jButtonMinimizar.setBackground(new java.awt.Color(0, 153, 153));
        jButtonMinimizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMinimizar.setText("-");
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimizar.setMaximumSize(new java.awt.Dimension(39, 21));
        jButtonMinimizar.setMinimumSize(new java.awt.Dimension(39, 21));
        jButtonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMouseExited(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(0, 153, 153));
        jButtonSair.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("X");
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSairMouseExited(evt);
            }
        });
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DraggedLayout = new javax.swing.GroupLayout(Dragged);
        Dragged.setLayout(DraggedLayout);
        DraggedLayout.setHorizontalGroup(
            DraggedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DraggedLayout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addComponent(jButtonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair)
                .addGap(21, 21, 21))
        );
        DraggedLayout.setVerticalGroup(
            DraggedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DraggedLayout.createSequentialGroup()
                .addGroup(DraggedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.add(Dragged);
        Dragged.setBounds(-6, 0, 590, 30);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabelRemetente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRemetente.setText("Remetente:");

        Remetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemetenteActionPerformed(evt);
            }
        });

        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha:");

        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelRemetente)
                    .addComponent(jLabelSenha)
                    .addComponent(Remetente, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(Senha, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRemetente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(150, 70, 430, 130);

        textMensagem.setColumns(20);
        textMensagem.setRows(5);
        jScrollPane1.setViewportView(textMensagem);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(170, 330, 370, 130);

        txtFile.setEditable(false);
        txtFile.setBackground(new java.awt.Color(0, 153, 153));
        txtFile.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtFile.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtFile);
        txtFile.setBounds(200, 470, 340, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnviarMouseEntered
        // TODO add your handling code here:
        jButtonEnviar.setBackground(new Color (0,51,51));
    }//GEN-LAST:event_jButtonEnviarMouseEntered

    private void jButtonEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnviarMouseExited
        // TODO add your handling code here
        jButtonEnviar.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_jButtonEnviarMouseExited

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // TODO add your handling code here:
        String REMETENTE = Remetente.getText();
        String SENHA = String.valueOf(Senha.getPassword());
        String DESTINATARIO = Destinatario.getText();
        String ASSUNTO = Assunto.getText();
        String TEXTMENSAGEM = textMensagem.getText();
        String ANEXO = txtFile.getText();
        String DATA = new MailSender().sendMail(REMETENTE, SENHA, DESTINATARIO, ASSUNTO, TEXTMENSAGEM, ANEXO);
        System.out.println(DATA);
        
        if(DATA.equals("true")){
        
            JOptionPane.showMessageDialog(this,"Email enviado com sucesso !");
        
        }else{
        
            JOptionPane.showMessageDialog(this,"Erro ao enviar o email !");
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonNovaMensagemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovaMensagemMouseEntered
        // TODO add your handling code here:
        jButtonNovaMensagem.setBackground(new Color (0,51,153));
    }//GEN-LAST:event_jButtonNovaMensagemMouseEntered

    private void jButtonNovaMensagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovaMensagemMouseExited
        // TODO add your handling code here:
        jButtonNovaMensagem.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_jButtonNovaMensagemMouseExited

    private void jButtonNovaMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaMensagemActionPerformed
        // TODO add your handling code here:
        new MailSender().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonNovaMensagemActionPerformed

    private void jButtonAnexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnexarActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Procurar arquivo");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        FileNameExtensionFilter filter = new  FileNameExtensionFilter("imagem", "jpg", "png", "txt");
        
        fileChooser.setFileFilter(filter);
        int retorno = fileChooser.showOpenDialog(this);
        if (retorno == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            txtFile.setText(file.getPath());
        }
        
    }//GEN-LAST:event_jButtonAnexarActionPerformed

    private void AssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssuntoActionPerformed

    private void DestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinatarioActionPerformed

    private void jButtonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarMouseClicked

    private void jButtonMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMouseEntered
        // TODO add your handling code here:
        jButtonMinimizar.setBackground(new Color (0,51,51));
    }//GEN-LAST:event_jButtonMinimizarMouseEntered

    private void jButtonMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMouseExited
        // TODO add your handling code here:
        jButtonMinimizar.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_jButtonMinimizarMouseExited

    private void jButtonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog (this, "A conexão está sendo encerrada!");
        System.exit(0);
    }//GEN-LAST:event_jButtonSairMouseClicked

    private void jButtonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseEntered
        // TODO add your handling code here:
        jButtonSair.setBackground(new Color (0,51,51));
    }//GEN-LAST:event_jButtonSairMouseEntered

    private void jButtonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseExited
        // TODO add your handling code here:
        jButtonSair.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_jButtonSairMouseExited

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void DraggedMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggedMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_DraggedMouseDragged

    private void DraggedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggedMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_DraggedMousePressed

    private void RemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemetenteActionPerformed

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MailSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MailSender().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Assunto;
    private javax.swing.JTextField Destinatario;
    private javax.swing.JPanel Dragged;
    private javax.swing.JLabel ImageIconMail;
    private javax.swing.JTextField Remetente;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JButton jButtonAnexar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonMinimizar;
    private javax.swing.JButton jButtonNovaMensagem;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelAssunto;
    private javax.swing.JLabel jLabelDestinatario;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelRemetente;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textMensagem;
    private javax.swing.JTextField txtFile;
    // End of variables declaration//GEN-END:variables
}
